stages:
  - build

variables:
  GIT_SUBMODULE_STRATEGY: normal

before_script:
  - echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
  - apk update
  - apk add musl-dev linux-headers meson ninja gcc scdoc
  - apk add libxkbcommon-dev cairo-dev yaml-dev librsvg-dev
  - apk add wayland-dev wayland-protocols wlroots-dev
  - apk add python3 py3-pip
  - apk add ttf-hack
  - apk add git

debug-x64:
  image: alpine:edge
  stage: build
  script:
    - mkdir -p bld/debug
    - meson --buildtype=debug fuzzel bld/debug
    - ninja -C bld/debug -k0
    - meson test -C bld/debug --print-errorlogs
  artifacts:
    reports:
      junit: bld/debug/meson-logs/testlog.junit.xml

debug-x86:
  image: i386/alpine:edge
  stage: build
  script:
    - mkdir -p bld/debug
    - meson --buildtype=debug fuzzel bld/debug
    - ninja -C bld/debug -k0
    - meson test -C bld/debug --print-errorlogs
  artifacts:
    reports:
      junit: bld/debug/meson-logs/testlog.junit.xml

release-x64:
  image: alpine:edge
  stage: build
  script:
    - mkdir -p bld/release
    - meson --buildtype=release fuzzel bld/release
    - ninja -C bld/release -k0
    - meson test -C bld/release --print-errorlogs
  artifacts:
    reports:
      junit: bld/release/meson-logs/testlog.junit.xml

release-x86:
  image: i386/alpine:edge
  stage: build
  script:
    - mkdir -p bld/release
    - meson --buildtype=release fuzzel bld/release
    - ninja -C bld/release -k0
    - meson test -C bld/release --print-errorlogs
  artifacts:
    reports:
      junit: bld/release/meson-logs/testlog.junit.xml

no-cairo-no-icons-x64:
  image: alpine:edge
  stage: build
  script:
    - mkdir -p bld/no-cairo-no-icons
    - meson --buildtype=release -Denable-cairo=disabled -Denable-png=disabled -Denable-svg=disabled fuzzel bld/no-cairo-no-icons
    - ninja -C bld/no-cairo-no-icons -k0
    - meson test -C bld/no-cairo-no-icons --print-errorlogs
  artifacts:
    reports:
      junit: bld/no-cairo-no-icons/meson-logs/testlog.junit.xml

codespell:
  image: alpine:edge
  stage: build
  script:
    - apk add python3
    - apk add py3-pip
    - pip install codespell
    - codespell *.c *.h
